ntnui/apps/forms/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url
from .form_types import FORM_TYPES

app_name = 'forms'
urlpatterns = [
    #path('3', FormTextSaverView.as_view(), name="Form Text Saver"),
    #path('4', FormTextTestView.as_view(), name="Form Text Test View"),
    path('incoming-list/', IncomingView.as_view(), name="incoming-list"),
    path('outgoing-list/', OutgoingView.as_view(), name="outgoing-list"),
    path('archive-incoming-list/', IncomingArchiveView.as_view(), name="archive-incoming-list"),
    path('archive-outgoing-list/', OutgoingArchiveView.as_view(), name="archive-outgoing-list"),
    path('signer-info/<str:slug>/<int:id>/', InfoView.as_view(), name="signer-info"),
    path('signed-form-info/<str:slug>/<int:id>/', SignedFormView.as_view(), name="signed-form-info"),
    path('instantiator/', InstantiatorView.as_view(), name="instantiator"),
    path('signer/<str:slug>/<int:id>/', SignerView.as_view(), name="signer"),
    path('', IncomingView.as_view(), name="forms-default"),
    path('sign/', SignView.as_view(), name='sign'),
]

ntnui/urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

# from accounts import views as accounts_views
# from groups import views as groups_views


''' Include URL Patterns '''
urlpatterns = [
    path('admin/', include('database.urls')),
    path('nested_admin/', include('nested_admin.urls')),
    path('api/', include('api.urls')),

    # Application routes
    path('a/', include('authentication.urls')),
    path('m/', include('management.urls')),
    path('f/', include('forms.urls')),
    re_path(r'^$', RedirectView.as_view(
        pattern_name='group-list', permanent=False))
    # url(r'^ajax/', include('forms.ajax')),
    # url(r'^$', groups_views.list_groups, name='home'),
    # url(r'^forms/', include('forms.urls')),
    # url(r'^groups/', include('groups.urls')),
    # url(r'^hs/', include('hs.urls')),
    # # url(r'^signup/$', accounts_views.signup, name='signup'),
    # url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(
    #     template_name='accounts/password_change.html'),
    #     name='password_change'),
    # url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(
    #     template_name='accounts/password_change_done.html'),
    #     name='password_change_done'),
    # url(r'^cron/accounts/all$', accounts_views.add_all_users_from_exeline,
    #     name='add_all_users_from_exeline'),
    # url(r'^cron/accounts/lastday$', accounts_views.add_last_week_users_from_exeline,
    #     name='add_last_week_users_from_exeline'),

    # Load static files
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ntnui/apps/forms/models/coach_form_model.py
from django.db import models
from django import forms
from forms.models import AbstractFormModel, enums, FormTextModel
from datetime import datetime

class CoachFormModel(AbstractFormModel):

    position = models.CharField(max_length = 128, choices=enums._POSITION, null=True)
    start_date = models.DateField(null=True)
    compensation = models.CharField(max_length = 128, choices=enums._COMPENSATIONS, null=True)
    compensation_comments = models.TextField(blank=True)

    form_name = "Midlertidig ansettelse"
    form_slug = 'coach'
    required_sign_type = 0
    actions = [
        "notify_signers",
        "notify_owner"
    ]

class CoachSigningForm(forms.ModelForm):
    class Meta:
        model = CoachFormModel
        fields = ['position', 'compensation', 'compensation_comments', 'start_date']
        labels = {
            'position': 'Posisjon',
            'compensation': 'Kompensasjon',
            'compensation_comments': 'Kommentarer',
            'start_date': 'Startdato',
        }
        widgets = {
            'position': forms.Select(attrs={'class': 'uk-select'}),
            'compensation': forms.Select(attrs={'class': 'uk-select'}),
            'start_date': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'value': datetime.now(),  'type':'date'}),
            'compensation_comments': forms.Textarea(attrs={'class': 'uk-textarea', 'rows':3}),
        }

ntnui/apps/forms/models/enums.py
_POSITION = (
    ("Trener", "Trener"),
    ("Oppmann", "Oppmann"),
    ("Instruktør", "Instruktør"),
    ("Hjelpetrener", "Hjelpetrener")
)

_COMPENSATIONS = (
    ("ingen", "ingen"),
    ("treningskort", "treningskort"),
    ("betalt reise", "betalt reise"),
    ("annet", "annet")
)

ntnui/apps/authentication/forms/user.py
from database.models import UserModel
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """

    def __init__(self, *args, **kargs):
        super(SignUpForm, self).__init__(*args, **kargs)
        self.fields.pop('username', None)

    class Meta:
        model = UserModel
        fields = ("email",)

ntnui/apps/forms/admin.py
from django.contrib import admin
from .models import AbstractFormModel, CoachFormModel, FormTextModel, TeamContractFormModel

admin.site.register(AbstractFormModel)
admin.site.register(CoachFormModel)
admin.site.register(FormTextModel)
admin.site.register(TeamContractFormModel)

ntnui/apps/forms/form_types.py
from forms.models import *
from forms.models import CoachSigningForm, CoachFormModel, TeamContractSigningForm, TeamContractFormModel

# Add here when creating a new type of form
"""
FORM_TYPES holds all the form_slugs of the respective form models.
Form slugs of new types of forms should be added here.
FORM_TYPES is used in InstantiateForm to fetch all the forms available for sending out.
"""
FORM_TYPES = {
    'coach': CoachFormModel,
    'teamcontract': TeamContractFormModel
}

"""
signing_forms holds all the django forms that are used for filling out their respective model forms.
When adding a new type of form, it's signing form should be added here.
"""
signing_forms = {
    CoachFormModel.form_slug: CoachSigningForm,
    TeamContractFormModel.form_slug: TeamContractSigningForm,

}

ntnui/apps/forms/tests.py
from django.test import TestCase

# Create your tests here.

ntnui/apps/forms/views/archived_list_view.py
from django.shortcuts import render
from django.views import View
from forms.models import AbstractFormModel
from forms.utils import form_utils

class IncomingArchiveView(View):

    def get(self, request):
        current_user = request.user
        forms = AbstractFormModel.objects.filter(form_signers=current_user,form_completed=True).order_by("-form_modified_time")
       
        context = {
            'forms': forms,
            'navbar': 'archive',
            'archive_navbar': 'incoming-list',
            'is_authorized': form_utils.is_authorized(current_user),
        }
        return render(request, 'archived_incoming_list.html', context)


class OutgoingArchiveView(View):

    def get(self, request):
        current_user = request.user
        forms = AbstractFormModel.objects.filter(form_instantiator=current_user, form_completed=True).order_by("-form_created_time")
        
        context = {
            'forms': forms,
            'navbar': 'archive',
            'archive_navbar': 'outgoing-list',
            'is_authorized': form_utils.is_authorized(current_user),
        }
        return render(request, 'archived_outgoing_list.html', context)

ntnui/apps/forms/views/info_view.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from forms.models import FormTextModel, AbstractFormModel
from django.http import HttpResponseForbidden

class InfoView(View):
    def get(self, request, slug, id):
        form_instance = get_object_or_404(AbstractFormModel, pk=id)
        form_text = FormTextModel.objects.get(id=form_instance.meta_version)
        signatures = form_instance.form_signatures.all()
        signers = form_instance.form_signers.all()
        user = request.user
        print(signatures)
        print(signers)
        if user in signatures or user not in signers:
            return HttpResponseForbidden()
        context = {
            'form_id': id,
            'form_text': form_text.form_text_content,
            'form_slug': slug
        }
        return render(request, 'form_info.html', context)

ntnui/apps/forms/views/instantiator_view.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse
from forms.models import FormTextModel
from forms.actions import Actions
from database.models import GroupModel
from ..form_types import *
from ..utils.form_utils import *
from django.core.exceptions import PermissionDenied
from forms.utils import form_utils
from forms.forms import InstantiateForm


class InstantiatorView(View):

    def get(self, request):
        try: 
            form = self.get_form(request)
        except PermissionDenied:
            return HttpResponseForbidden()
        current_user = request.user
        context = {
            'navbar': 'instantiator',
            'form': form,
            'is_authorized': form_utils.is_authorized(current_user),
            'current_user': current_user,
        }
        return render(request, 'form_instantiator.html', context)

    """
    post() creates a new instance of the chosen form type.
    """
    def post(self, request):
        try: 
            form = self.get_form(request)
        except PermissionDenied:
            return HttpResponseForbidden()
        if form.is_valid():
            slug = form.cleaned_data['form_slug']
            group = form.cleaned_data['group']
            signee = form.cleaned_data['form_signers']
            model_instance = FORM_TYPES[slug].objects.create()
            model_instance.form_signers.add(signee)
            model_instance.group = GroupModel.objects.get(group_id=group)
            model_instance.form_instantiator = request.user
            actions = Actions(model_instance)
            actions.do()
            # get formtext with highest primary key
            form_text_id = FormTextModel.objects.filter(form_slug=slug).last().id
            setattr(model_instance, 'meta_version', form_text_id)
            # model_instance.notify_signers()
            model_instance.save()
            return HttpResponseRedirect(reverse('forms:outgoing-list'))
        else:
            return "invalid form"


    """
    get_form() sets up the InstantiateForm with valid choices.
    A group is valid if a user is the leader of the group.
    The form signers are restricted to the group members.
    If there is only one valid group, it is chosen by default and can't be changed.
    When there are multiple groups, the view is refreshed on change to filter the form signers again.
    """
    def get_form(self,request):
        current_user = request.user
        leader_groups = get_leader_groups(current_user)
        if not leader_groups:
            raise PermissionDenied

        groups = tuple([(group.group_id, group) for group in leader_groups])
        group = request.GET.get('group')
        if not group:
            group = groups[0][0]
        else:
            # makes sure that the group from the URL is valid
            valid_group = False
            for g in groups:
                if int(g[0]) == int(group):
                    valid_group = True
                    break
            if not valid_group:
                raise PermissionDenied

        members = GroupModel.objects.get(group_id=group).members.filter()
        form_signers = tuple([(user.ntnui_no, user) for user in members])
        if request.POST:
            return InstantiateForm(form_signers, group, groups, request.POST)
        else:
            return InstantiateForm(form_signers, group, groups)

ntnui/apps/forms/views/list_view.py
from django.shortcuts import render
from django.views import View
from forms.models import AbstractFormModel
from forms.utils import form_utils


class IncomingView(View):

    def get(self, request):
        current_user = request.user
        forms = AbstractFormModel.objects.filter(form_signers=current_user).filter(form_completed=False).order_by("-form_created_time")

        context = {
            'current_user': current_user,
            'forms': forms,
            'navbar': 'incoming-list',
            'is_authorized': form_utils.is_authorized(current_user),
        }
        return render(request, 'incoming_list.html', context)


class OutgoingView(View):

    def get(self, request):
        current_user = request.user
        forms = AbstractFormModel.objects.filter(form_instantiator=current_user).filter(form_completed=False).order_by("-form_created_time")

        context = {
            'forms': forms,
            'navbar': 'outgoing-list',
            'is_authorized': form_utils.is_authorized(current_user),
        }
        return render(request, 'outgoing_list.html', context)

ntnui/apps/forms/views/sign.py
"""
SignView

This view is presented to the user when the user generate the signature.
The current system supports only password authentication, but higher order types
of authentication should be implementet as future work.

Required signature type/level are specified in abstract_form_model.py.
Available labels are:
    0: password authentication
    1: paper signature or BankID

"""

from django.shortcuts import render
from django.views import View
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse

from forms.models import *
from forms.forms import SignForm
from forms.actions import Actions

class SignView(View):
    def get(self, request):
        sign_level = request.session.get('sign_level', 1)  # fallback on high sign level (1)

        if sign_level == 1:
            return HttpResponse('paper signature or BankID required')

        form = SignForm()
        return render(request, 'confirm_password.html', {'form': form})

    def post(self, request):
        sign_level = request.session.get('sign_level', 1)
        record_id = request.session.get('record_id', False)
        record = AbstractFormModel.objects.get(id=record_id)

        if sign_level == 1:
            return HttpResponse('paper signature or BankID required')

        password_form = SignForm(request.POST)
        if password_form.is_valid():
            password = password_form.cleaned_data['password']
            if request.user.check_password(password):
                record.form_signatures.add(request.user)
                if record.is_form_completed():
                    record.form_completed = True
                record.save()
                try:
                    actions = Actions(record)
                    actions.do()
                except:
                    pass
                return HttpResponseRedirect(reverse('forms:archive-incoming-list'))
        password_form.add_error(None, "Feil passord")
        return render(request, 'confirm_password.html', {'form': password_form})

ntnui/apps/forms/views/signed_form_view.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from ..models import AbstractFormModel, FormTextModel
from ..utils import form_utils
from django.http import HttpResponseForbidden
from ..form_types import *


class SignedFormView(View):

    def get(self, request, slug, id):
            current_user = request.user
            record = get_object_or_404(AbstractFormModel, pk=id)
            form_text = FormTextModel.objects.get(id=record.meta_version)
            form = signing_forms[slug](request.POST or None, instance=record)

            if current_user not in record.form_signers.all() and current_user.ntnui_no != record.form_instantiator.ntnui_no:
                return HttpResponseForbidden()

            context = {
                'current_user': current_user,
                'record': record,
                'form': form,
                'form_text': form_text.form_text_content,
                'is_authorized': form_utils.is_authorized(current_user),
            }
            return render(request, 'form_signed_info.html', context)

ntnui/apps/forms/views/signer_view.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from ..form_types import signing_forms
from forms.models import AbstractFormModel
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse


class SignerView(View):
    def get(self, request, slug, id): 
        # Gets the joined form thanks to inheriting from polymorphic model
        record = get_object_or_404(AbstractFormModel, pk=id)
        form = signing_forms[slug](request.POST or None, instance=record)
        signatures = record.form_signatures.all()
        signers = record.form_signers.all()
        user = request.user
        if user in signatures or user not in signers:
            return HttpResponseForbidden()
        else:
            context = {
                'form': form,
                'id': record.id,
                'record': record,
            }
        return render(request, 'form_signer.html', context)

    def post(self, request, slug, id):
        record = AbstractFormModel.objects.get(id=id)
        form = signing_forms[slug](request.POST or None, instance=record)
        request.session['record_id'] = id
        request.session['sign_level'] = record.get_required_sign_level()

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('forms:sign'))
        return render(request, 'form_signer.html', {'form': form, 'id': record.id})

ntnui/apps/forms/templates/archived_incoming_list.html
{% extends 'form_navbar.html' %}

{% block navbar_content %}

    <div class="uk-container uk-width-4-5@m uk-width-2-3@l uk-margin-small-top">
    {%  if is_authorized %}
    <h2 class="uk-heading-divider">Fullførte mottatte skjema</h2>
    {% else %}
    <h2 class="uk-heading-divider">Signerte skjema</h2>
    {% endif %}
    {% if forms %}
        <p>Disse skjema har du signert og har blitt godkjent.</p>
            <table class="uk-table uk-table-divider">
            <thead>
                <tr>
                    <th>Signert dato</th>
                    <th>Skjema</th>
                    <th>Gruppe</th>
                    <th>Fra</th>
                    <th>Godkjenner</th>
                </tr>
            </thead>
            <tbody>
                {% for form in forms %}
                    <tr>
                    <td>{{ form.form_modified_time|date:'d-M-Y' }}</td>
                    <td>
                        <a href="{% url 'forms:signed-form-info' slug=form.form_slug id=form.id %}">
                            {{ form.form_name }}
                        </a>
                    </td>
                    <td>{{ form.group }}</td>
                    <td>{{ form.form_instantiator }}</td>
                    <td>
                        {%  if form.form_approvers.all %}
                        {% for approver in form.form_approvers.all %}
                            <p>
                                {{ approver }}
                            </p>
                        {% endfor %}
                        {% else %}
                            Ingen
                        {% endif %}
                    </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>

    {% else %}
        Det finnes ingen skjema her enda. Her vil du finne skjema du har signert og som har blitt godkjent.
    {% endif %}
    </div>

{% endblock %}

ntnui/apps/forms/templates/archived_outgoing_list.html
{% extends 'form_navbar.html' %}

{% block navbar_content %}

    <div class="uk-container uk-width-4-5@m uk-width-2-3@l uk-margin-small-top" >
    <h2 class="uk-heading-divider">Fullførte utsendte skjema</h2>

    {% if forms %}
        <p>Disse skjema har du sendt ut og har blitt fullført.</p>
            <table class="uk-table uk-table-divider">
            <thead>
                <tr>
                    <th>Opprettet</th>
                    <th>Skjema</th>
                    <th>Gruppe</th>
                    <th>Til</th>
                    <th>Godkjenner</th>
                </tr>
            </thead>
            <tbody>
                {% for form in forms %}
                    <tr>
                    <td>{{ form.form_created_time|date:'d-M-Y' }}</td>
                    <td>
                        <a href="{% url 'forms:signed-form-info' slug=form.form_slug id=form.id %}">
                            {{ form.form_name }}
                        </a>
                    </td>
                    <td>{{ form.group }}</td>
                    <td>
                        {% for signer in form.form_signers.all %}
                            <p>
                                {{ signer }} -
                                {% if signer in form.form_signatures.all %}
                                signert
                                {% else %}
                                ikke signert
                                {% endif %}
                            </p>
                        {% endfor %}
                    </td>
                    <td>
                        {%  if form.form_approvers.all %}
                        {% for approver in form.form_approvers.all %}
                            <p>
                                {{ approver }}
                            </p>
                        {% endfor %}
                        {% else %}
                            Ingen
                        {% endif %}
                    </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>

    {% else %}
        Det finnes ingen skjema her.
    {% endif %}


    </div>

{% endblock %}

ntnui/apps/forms/templates/confirm_password.html
{% extends 'authentication_card.html' %} 

{% load static %} 

{% block card-title %}
    Bekreft ditt passord
{% endblock %}

{% block card-button %}
    <button class="uk-button uk-button-default uk-align-center uk-margin-remove-bottom">Signer</button>
{% endblock %}

ntnui/apps/forms/templates/form.html
{% extends 'base.html' %}

{% block content %}

<div class="uk-container uk-width-4-5@m uk-width-2-3@l uk-margin-small-top">
    <div class="uk-flex uk-flex-column uk-flex-middle uk-width-1-1">
      {% block form-content %}
      {% endblock %}
    </div>
  </div>

{% endblock %}

ntnui/apps/forms/templates/form_info.html
{% extends 'form.html' %}

{% block form-content %}

<div class="uk-container uk-width-6-7@m">

    {{ form_text | safe }}

        <p>
            <!--label><input class="uk-checkbox" type="checkbox" unchecked> Jeg bekrefter å ha lest innholdet over</label>
            <br><br-->
            <form action="{% url 'forms:signer' slug=form_slug id=form_id %}" >
                <input type="submit" value="Til utfylling" class="uk-button uk-button-secondary" />
            </form>
        </p>
        <hr>

</div>
{% endblock %}

ntnui/apps/forms/templates/form_navbar.html
<!-- Should be inherited by all templates that should include graphic and navbar -->

{% extends 'base.html' %}

{% load static %}

{% block content %}
     <div class="uk-cover-container">
        <canvas class="uk-visible@m" width="0" height="200" ></canvas>
        <canvas class="uk-hidden@m" width="0" height="200" ></canvas>
        <img src="/media/forms/forms_photo.png" alt="group cover photo" uk-cover>
    </div>

    <nav class="uk-navbar-container">
        <div class="uk-flex uk-flex-center uk-flex-middle uk-width-1-1">
            <ul class="uk-tab uk-subnav uk-subnav-divider uk-margin-remove uk-padding-small"  uk-margin>
               {% if is_authorized %}
                <li {% if navbar == 'instantiator' %}class="uk-active"{% endif %}>
                    <a href="{% url 'forms:instantiator' %}" >
                        <span uk-icon="copy" class="uk-margin-small-right" ></span>
                        Send skjema
                    </a>
                </li>
                <li {% if navbar == 'outgoing-list' %}class="uk-active"{% endif %}>
                    <a href="{% url 'forms:outgoing-list' %}">
                        <span uk-icon="forward" class="uk-margin-small-right"></span>
                        Utsendte skjema
                    </a>
                </li>
                {% endif %}
                <li {% if navbar == 'incoming-list' %}class="uk-active"{% endif %}>
                    <a href="{% url 'forms:incoming-list' %}" >
                        <span uk-icon="file-edit" class="uk-margin-small-right"></span>
                        Mottatte skjema
                    </a>
                </li>
                {% if is_authorized %}
                <li {% if navbar == 'archive' %}class="uk-active"{% endif %}>
                    <a href="#"><span uk-icon="album" class="uk-margin-small-right"></span>
                        Fullførte Skjema
                        <span class="uk-margin-small-left" uk-icon="icon: triangle-down"></span></a>
                        <div uk-dropdown="mode: click">
                            <ul class="uk-nav uk-dropdown-nav">
                                <li class="uk-active">
                                    <a href="{% url 'forms:archive-outgoing-list' %}" >Utsendte skjema</a>
                                    <a href="{% url 'forms:archive-incoming-list' %}" >Mottatte skjema</a>
                                </li>
                            </ul>
                        </div>
                </li>
                    {% else %}
                    <li {% if navbar == 'archive' %}class="uk-active"{% endif %}>
                        <a href="{% url 'forms:archive-incoming-list' %}" >
                            <span uk-icon="album" class="uk-margin-small-right"></span>
                            Signerte skjema
                        </a>
                    </li>
                    {% endif %}
            </ul>
        </div>
    </nav>
    {% block navbar_content %}
    {% endblock %}
{% endblock %}

ntnui/apps/forms/templates/incoming_list.html
{% extends 'form_navbar.html' %}

{% block navbar_content %}

    <div class="uk-container uk-width-4-5@m uk-width-2-3@l uk-margin-small-top">
    {%  if is_authorized %}
    <h2 class="uk-heading-divider">Mottatte skjema</h2>
    {% else %}
    <h2 class="uk-heading-divider">Mottatte skjema</h2>
    {% endif %}
    {% if forms %}
        <p>Disse skjema venter på din signatur eller venter på ekstern godkjenning. Klikk på skjemaet du ønsker å signere.<br>
        <a href="{% url 'forms:archive-incoming-list' %}">
            Finner du ikke motatt skjema? Kanskje det er fullført, klikk her for å se fullførte skjema.
        </a>
        </p>
            <table class="uk-table uk-table-divider">
            <thead>
                <tr>
                    <th>Opprettet</th>
                    <th>Skjema</th>
                    <th>Gruppe</th>
                    <th>Fra</th>
                    <th>Signert</th>
                    <th>Godkjenner</th>
                </tr>
            </thead>
            <tbody>
                {% for form in forms %}
                    <tr>
                    <td>{{ form.form_created_time|date:'d-M-Y' }}</td>
                    <td>
                        {% if current_user not in form.form_signatures.all %}
                            <a href="{% url 'forms:signer-info' slug=form.form_slug id=form.id %}">
                        {% else %}
                            <a href="{% url 'forms:signed-form-info' slug=form.form_slug id=form.id %}">
                        {% endif %}
                                {{ form.form_name }}
                            </a>
                    </td>
                    <td>
                        {{ form.group }}
                    </td>
                    <td>
                        {{ form.form_instantiator }}
                    </td>
                    <td>
                        {% if current_user in form.form_signatures.all %}
                            Ja
                        {% else %}
                            Nei
                        {% endif %}
                    </td>
                    <td>
                        {%  if form.form_approvers.all %}
                        {% for approver in form.form_approvers.all %}
                            <p>
                                {{ approver }}
                            </p>
                        {% endfor %}
                        {% else %}
                            Ingen
                        {% endif %}
                    </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>

    {% else %}
        Du har ikke fått noen skjema som venter din signering.
        <br>
        <a href="{% url 'forms:archive-incoming-list' %}">
            Finner du ikke motatt skjema? Kanskje det er fullført, klikk her for å se fullførte skjema.
        </a>
    {% endif %}

    </div>

{% endblock %}

ntnui/apps/forms/templates/outgoing_list.html
{% extends 'form_navbar.html' %}

{% block navbar_content %}

<div class="uk-container uk-width-4-5@m uk-width-2-3@l uk-margin-small-top">
    <h2 class="uk-heading-divider">Utsendte skjema</h2>
    {% if forms %}
        <p>Disse skjema har du sendt ut og ikke er fullført enda.<br>
        <a href="{% url 'forms:archive-outgoing-list' %}">
             Finner du ikke utsendt skjema? Kanskje det er fullført, klikk her for å se fullørte skjema.
        </a>
        </p>
            <table class="uk-table uk-table-divider">
            <thead>
                <tr>
                    <th>Opprettet</th>
                    <th>Skjema</th>
                    <th>Gruppe</th>
                    <th>Til</th>
                    <th>Godkjenner</th>
                </tr>
            </thead>
            <tbody>
                {% for form in forms %}
                    <tr>
                    <td>{{ form.form_created_time|date:'d-M-Y' }}</td>
                    <td>{{ form.form_name }}</td>
                    <td>{{ form.group }}</td>
                    <td>
                        {% for signer in form.form_signers.all %}
                            <p>
                                {{ signer }} -
                                {% if signer in form.form_signatures.all %}
                                signert
                                {% else %}
                                ikke signert
                                {% endif %}
                            </p>
                        {% endfor %}
                    </td>
                    <td>
                        {%  if form.form_approvers.all %}
                        {% for approver in form.form_approvers.all %}
                            <p>
                                {{ approver }}
                            </p>
                        {% endfor %}
                        {% else %}
                            Ingen
                        {% endif %}
                    </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>

    {% else %}
        Her vil du finne skjema som du har sendt ut og ikke har blitt signert enda.
        Du har ingen utsendte skjema og listen er derfor tom.
        <br>
        <a href="{% url 'forms:archive-outgoing-list' %}">
             Finner du ikke utsendt skjema? Kanskje det er fullført, klikk her for å se fullørte skjema.
        </a>
    {% endif %}

    </div>

{% endblock %}